## CHANGE this to the name of your plugin.
name: RPGAddon

## CHANGE this to your username.
author: ItsTheSky

## CHANGE this to a meaninful but short description of your plugin.
description: Addon développé par ItsTheSky pour le RPG de HallOfGames

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.CHANGEME.slimefunaddon.ExampleAddon

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14
